spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhd-webpage
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR_CLIENT_ID
            clientSecret: YOUR_CLIENT_SCERET
            scope:
              - email
              - profile
