spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhd-webpage
    username: root
    password: ${HHD_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${HHD_CLIENT_ID}
            clientSecret: ${HHD_CLIENT_SCERET}
            scope:
              - email
              - profile
